### ISSUE TITLE
如何替换ASRT v0.6.0 Released模型

### ISSUE THREAD

**Issue by linshihang** [AnnaClancy/AndroidSpeechRecognition#1]
您好，我想把模型替换成最新的v0.6.0，请问要怎么把speech_model251_e_0_step_625000.model和speech_model251_e_0_step_625000.model.base变成你的model.pb文件？

**Comment by AnnaClancy** [comment]
您好。模型配置由开源 python 脚本支持，走[这里](https://github.com/amir-abdi/keras_to_tensorflow)。
另外在模型文件替换后，需要修改 [Chain](https://github.com/AnnaClancy/AndroidSpeechRecognition/blob/master/app/src/main/java/com/annaclancy/demo0419/Chain.java) 类下 DICT_LENGTH 长度（目前存在书写规范问题，1422/1421的位置也需要检查），与现有模型长度（隐约记得 6.0 版本有改动）匹配，才能使其正确生效。
