### ISSUE TITLE
这个代码可以在PC端的语音识别什么使用吗？

### ISSUE THREAD

**Issue by Chenpuh** [AnnaClancy/AndroidSpeechRecognition#2]
你好。这个代码可以在PC端的语音识别什么使用吗？还是只能用于Android？

**Comment by AnnaClancy** [comment]
您好。该 APP 本身是 pc python 对 Android Java 的移植，在 pc 端上通过编译器运行很难检验实际效果。

**Comment by Chenpuh** [comment]
好吧，谢谢啦
